changelog:
  categories:
    - title: 🔒 Security
      labels:
        - security
    - title: 🚀 Features
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 📖 Documentation
      labels:
        - documentation
    - title: 🏗️ Backend
      labels:
        - backend
    - title: 🎨 Frontend
      labels:
        - frontend
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 🔧 Other Changes
      labels:
        - "*"
